### ISSUE TITLE
不支持excludeJarFilter了？

### ISSUE THREAD

**Issue by zirconnnn** [sensorsdata/sa-sdk-android-plugin2#1]
还是说不需要了？

**Comment by wangzhzh** [comment]
sa-sdk-android-plugin2不支持，sa-sdk-android-plugin支持
区别：
sa-sdk-android-plugin2：不支持hook第三方的lib，但支持instant run，也支持buildCache，编译速度比较快
sa-sdk-android-plugin：支持hook第三方的lib，但不支持instant run，也不指出buildCache，编译速度比较慢

**Comment by zirconnnn** [comment]
了解，多谢。
