### ISSUE TITLE
load class in gradle plugin

### ISSUE THREAD

**Issue by ethanhua** [sensorsdata/sa-sdk-android-plugin2#12]
the plugin is nice，i have an question when i read the source code, the question is that why you use URLClassLoader for load webview related class, the URLClassLoader created by traverseing transformInvocation which will cost some time, the method `Class.forName`  doesn't meet your needs?

**Comment by dengshiwei** [comment]
At compile time, Class.forName doesn't work。

**Comment by GvcZhang** [comment]
`ASM` just handles class files, so we need a way to check class if a webview‘s child, DiDi's Booster project is using the way. Another way is building the class’s inheritance relationship when traverse class files like TikTok's ByteX does.

**Comment by ethanhua** [comment]
> At compile time, Class.forName doesn't work。

thank you for your reply. i got it . and can you explain why Class.forName doesn't work in detail? thanks

**Comment by dengshiwei** [comment]
@ethanhua I think `Class.forName`  is a method of reflection, applicable at runtime, while ASM is a compiler processing bytecode
