### ISSUE TITLE
子模块中引入

### ISSUE THREAD

**Issue by sulovely** [sensorsdata/sa-sdk-android-plugin2#15]
在子模块中引入的话，build应该怎么配置呢？

**Comment by dengshiwei** [comment]
@sulovely 目前我们的插件只能使用 application 工程，集成方式可以参照我们的集成文档：https://manual.sensorsdata.cn/sa/latest/page-1573907.html

**Comment by dengshiwei** [comment]
@sulovely 目前我们已经支持 Library 类型，但是需要源码集成我们的 SDK。
<img width="483" alt="image" src="https://user-images.githubusercontent.com/12447711/170619666-bc78cd51-fedb-40a5-a8d0-f9e5c6dcbbf1.png">
