### ISSUE TITLE
插件里默认exclude的一些包能否支持修改

### ISSUE THREAD

**Issue by qq549631030** [sensorsdata/sa-sdk-android-plugin2#19]
在SensorsAnalyticsTransformHelper的exclude里内置了一些包名，所有以这些开头的类都无法埋点，比如‘com.google.android’，我想埋com.google.android.exoplayer2.ui.PlayerControlView里的播放、暂停按钮的话插件自动排除了。
希望能给个机会让我修改exclude里的包名

**Comment by GvcZhang** [comment]
@qq549631030 目前线上版本无法满足你这个需求。

如果你想要满足您的这个功能，你可以按照如下步骤来操作：
1. 下载插件源码
2. 修改 `SensorsAnalyticsTransformHelper`类，在其中的 special 中添加对应的类或者包名：
```
class SensorsAnalyticsTransformHelper {
///
    /** 将一些特例需要排除在外 */
    public static final HashSet<String> special =
['android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener',
  ...
 'android.support.v7.widget.ActionMenuPresenter$OverflowMenuButton']

```
3. 编译插件
```
./gradlew uploadArchives
```
执行上述命令打包，会在工程中出现 repo 目录

4. 按照如下步骤集成本地的插件即可
<img width="1086" alt="集成插件步骤" src="https://user-images.githubusercontent.com/45255699/145751675-cacdf171-3261-4d1c-9c19-26664bd0fd19.png">

**Comment by qq549631030** [comment]
好的，感谢！
发现直接在gradle适当位置加上修改special就可以了，不用打本地包：
SensorsAnalyticsTransformHelper.special.add('com.google.android.exoplayer2.ui.PlayerControlView$ComponentListener')
要是能在SensorsAnalyticsExtension里多一个special的配置就更好了
