### ISSUE TITLE
Google官方Fragment页面框架Navigation, Fragment跳转埋点支持

### ISSUE THREAD

**Issue by xiaoqiangchongchongchong** [sensorsdata/sa-sdk-android-plugin2#22]
页面跳转也是埋点记录的一部分，请教一下，我们为什么没有支持navigation跳转的自动化埋点。

**Comment by dengshiwei** [comment]
@xiaoqiangchongchongchong 目前我们采集页面浏览，你们使用页面跳转一般用于什么分析呢

**Comment by xiaoqiangchongchongchong** [comment]
> @xiaoqiangchongchongchong 目前我们采集页面浏览，你们使用页面跳转一般用于什么分析呢

也是对用户行为的一种跟踪，比如 我们希望能收集到 从用户点击按钮，跳转，页面生命周期变化的全链路。
感谢回复，页面浏览采集也是够用的。
