### ISSUE TITLE
引入神策插件后无法统计测试覆盖率

### ISSUE THREAD

**Issue by hoop208** [sensorsdata/sa-sdk-android-plugin2#25]
开启测试覆盖率testCoverageEnabled true后生成的apk无法安装

`
debug {
            testCoverageEnabled true
        }
`
报错信息:
Installation did not succeed.
The application could not be installed: INSTALL_FAILED_INVALID_APK

**Comment by dengshiwei** [comment]
这个跟插件的关系应该不大
