### ISSUE TITLE
单元测试无法编译通过：未检测到神策 Android SDK

### ISSUE THREAD

**Issue by qlang122** [sensorsdata/sa-sdk-android-plugin2#27]
未检测到神策 Android SDK，请参考如下文档检查集成步骤是否正确：
https://manual.sensorsdata.cn/sa/latest/tech_sdk_client_android_basic-32506144.html
如需关闭此提示，请添加插件配置: disableCheckSdk=true

**Comment by tianjyan** [comment]
同样的问题

**Comment by tianjyan** [comment]
看了下[代码](https://github.com/sensorsdata/sa-sdk-android-plugin2/blob/master/plugin/src/main/groovy/com/sensorsdata/analytics/android/plugin/SensorsAnalyticsPlugin.groovy#L34 )，`SensorsAnalyticsPlugin` 会把`sensorsAnalytics`的值转换成配置文件，所以在build.gradle（module的）里面添加如下可以绕过检测：

```Groovy
sensorsAnalytics {
    disableCheckSDK = true
}
```

亲测可用

**Comment by qlang122** [comment]
nice，我也试试

**Comment by igilbert** [comment]
> ```groovy
> disableCheckSDK 
> ```

log提示的配置key是小写disableCheckSdk，而生效的是disableCheckSDK. 貌似提示错误
