### ISSUE TITLE
有適配 gradle 8.0 的排期嗎？

### ISSUE THREAD

**Issue by KingsleyWu** [sensorsdata/sa-sdk-android-plugin2#31]

**Comment by extmkv** [comment]
+1 This is blocking our project to be updated to Gradle 8 / AGP 8.

**Comment by extmkv** [comment]
@dengshiwei @liuweiqiang2016 please take a look

**Comment by liuweiqiang2016** [comment]
预计 5 月底发布 
It is expected to be released in late May.

**Comment by extmkv** [comment]
Any new about this topic?

**Comment by liuweiqiang2016** [comment]
It's scheduled for release on May 31.

**Comment by liuweiqiang2016** [comment]
各位抱歉，我们在发版过程中遇到一些问题，我们将尽快解决这些问题并希望在本周内完成发版。

Sorry everyone, we have encountered some problems in the process of releasing the version. We will solve these problems as soon as possible and hope to complete the release within this week.

**Comment by geekkoz** [comment]
🤞

**Comment by liuweiqiang2016** [comment]
好消息！v4.0.0-beta 已发布，支持 AGP 8.0 及以上版本，并支持 plugins DSL 集成，使用文档见：https://manual.sensorsdata.cn/sa/latest/page-129827590.html。

Good news! v4.0.0-beta has been released with support for AGP 8.0 + and plugins DSL. Documentation: https://manual.sensorsdata.cn/sa/latest/page-129827590.html.
