### ISSUE TITLE
onTabChanged的lambda hook会误将Rxjava2的方法注入

### ISSUE THREAD

**Issue by yzhiw** [sensorsdata/sa-sdk-android-plugin2#5]
ArrayList<String> al = new ArrayList<>();
Observable.just(al).subscribeOn(Schedulers.io()).map(it -> it.get(4)).subscribe(it -> {
                });
这里it -> 输入也是一个String，与下面的方法描述一致。sLambdaMethods.put('(Ljava/lang/String;)V', new SensorsAnalyticsMethodCell(
                'onTabChanged',
                '(Ljava/lang/String;)V',
                'android/widget/TabHost$OnTabChangeListener',
                'trackTabHost',
                '(Ljava/lang/String;)V',
                1, 1,
                [Opcodes.ALOAD]))

**Comment by renqingyou** [comment]
你好，我是神策工程师，为了获得更多的问题细节，麻烦加一下微信 renqyhappy, 谢谢！

**Comment by renqingyou** [comment]
我们内部正在排查修改 @yzhiw

**Comment by wangzhzh** [comment]
v3.0.6 已 fix

**Comment by wangzhzh** [comment]
目前发现了新的问题，还在紧急修复中

**Comment by wangzhzh** [comment]
v3.0.6 已 fix
https://github.com/sensorsdata/sa-sdk-android-plugin2/releases/tag/v3.0.6
