### ISSUE TITLE
未找到methodCell变量定义的地方

### ISSUE THREAD

**Issue by hanchanpo13** [sensorsdata/sa-sdk-android-plugin2#6]
https://github.com/sensorsdata/sa-sdk-android-plugin2/blob/59146b54b88acb3b262ad5b17ca2703d9830eacc/plugin/src/main/groovy/com/sensorsdata/analytics/android/plugin/SensorsAnalyticsClassVisitor.groovy#L168

**Comment by dengshiwei** [comment]
@hanchanpo13 这是 groovy 的 for-in 语法，例如：
```groovy
class Example {
   static void main(String[] args) {
      def employee = ["Ken" : 21, "John" : 25, "Sally" : 22];
		
      for(emp in employee) {
         println(emp);
      }
   }
}
```

**Comment by hanchanpo13** [comment]
好的谢谢大佬调教
