### ISSUE TITLE
gradle导入sa-sdk-android-plugin2为什么不行

### ISSUE THREAD

**Issue by zzwfelixberto** [sensorsdata/sa-sdk-android-plugin2#8]
gradle导入sa-sdk-android-plugin2为什么不行

**Comment by dengshiwei** [comment]
你能详细描述下你的需求吗？
1. 你是需要将 sa-sdk-android-plugin2 导入到 Android Studio 项目中，出现错误吗？
2. 如果你需要引用插件，请参照我们的[官方的引用方式](https://manual.sensorsdata.cn/sa/latest/page-1573907.html)。

**Comment by zzwfelixberto** [comment]
报这个
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.sensorsdata.analytics.android']



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"清风徐来"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 上午10:03
收件人:&nbsp;"sensorsdata/sa-sdk-android-plugin2"<sa-sdk-android-plugin2@noreply.github.com&gt;;
抄送:&nbsp;"张志伟"<1351894920@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sensorsdata/sa-sdk-android-plugin2] gradle导入sa-sdk-android-plugin2为什么不行 (#8)





 
你能详细描述下你的需求吗？
  
你是需要将 sa-sdk-android-plugin2 导入到 Android Studio 项目中，出现错误吗？
 
如果你需要引用插件，请参照我们的官方的引用方式。

**Comment by dengshiwei** [comment]
@zzwfelixberto 您这边使用的插件是哪个版本？

**Comment by zzwfelixberto** [comment]
'com.sensorsdata.analytics.android:android-gradle-plugin2:3.2.4'
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"清风徐来"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 上午10:49
收件人:&nbsp;"sensorsdata/sa-sdk-android-plugin2"<sa-sdk-android-plugin2@noreply.github.com&gt;;
抄送:&nbsp;"张志伟"<1351894920@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [sensorsdata/sa-sdk-android-plugin2] gradle导入sa-sdk-android-plugin2为什么不行 (#8)





 
@zzwfelixberto 您这边使用的插件是哪个版本？

**Comment by dengshiwei** [comment]
辛苦你加入下我们的支持 QQ 群，我们有同学专门支持下你。在zhe'li这里回复有点慢。
![image](https://user-images.githubusercontent.com/12447711/83831729-97716200-a71a-11ea-8c6c-e2e68e5d4a57.png)

**Comment by dengshiwei** [comment]
@zzwfelixberto 您这边如果方便能发下你的引用方式的截图，或者弄个 Demo 吗?

**Comment by dengshiwei** [comment]
@zzwfelixberto 你这边的问题解决了吗？

**Comment by GvcZhang** [comment]
@dengshiwei 长时间没有回复，可以关闭
